### ISSUE TITLE
Warning: React.createElement: type is invalid

### ISSUE THREAD

**Issue by diequinteros** [Pau1fitz/react-slidez#10]
Im getting this error when putting the sample code in my project

"Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object."

This is how im using it, i got something wrong?

```javascriptimport img1 from './img/1.jpg';
import img2 from './img/2.jpg';
import img3 from './img/3.jpg';
let images = [
  img1,
  img2,
  img3
];
const Slideshow = require('react-slidez');
return (<Slideshow
  showIndex
  showArrows
  autoplay
  enableKeyboard
  useDotIndex
  slideInterval={2000}
  defaultIndex={1}
  slides={images}
  effect={'fade'}
/>);
```

**Comment by Pau1fitz** [comment]
hey @diequinteros it works fine for me with the following set up.

```
import React, { Component } from 'react';
import Slideshow from 'react-slidez';

import img from './img.jpg';
import img2 from './img2.jpg';
let images = [
  img,
  img2
];

class App extends Component {
  render() {
    return (
      <div className="App">
      <Slideshow
        showIndex
        showArrows
        autoplay
        enableKeyboard
        useDotIndex
        slideInterval={2000}
        defaultIndex={1}
        slides={images}
        effect={'fade'}
        />
      </div>
    );
  }
}

export default App;

```

Have you used `create-react-app` to bootstrap your project? are you even using React?

**Comment by diequinteros** [comment]
Actually i want implement in an already existing react project, the unique diferense with ur code is that im using function component not class

**Comment by Pau1fitz** [comment]
the fact you are using a function component shouldn't make a difference - see [here](https://codesandbox.io/s/m7yxnnmy69).

Can you paste the code of the whole component here?
