### ISSUE TITLE
seeing arrows + activity but no pictures - using local images

### ISSUE THREAD

**Issue by SeanFelipe** [Pau1fitz/react-slidez#7]
Hello !

I've got the slideshow component installed and I'm seeing the dots, arrows and the index is incrementing at the bottom. However no pictures are showing.

I'm able to render the pictures statically in an `<img>` tag so the pics are valid.

Can I add logging to the react-slidez code somehow and import the changed code so I can debug the slideshow didMount() and render() functions ?

**Comment by Pau1fitz** [comment]
Think I saw this too, I am out at the moment but will have a look tomorrow and let you know.

**Comment by Pau1fitz** [comment]
@SeanFelipe can you paste your code here?

**Comment by SeanFelipe** [comment]
```import React, { Component } from 'react'
import Slideshow from 'react-slidez'
import './App.css';


class App extends Component {

  constructor(props) {
    super(props)

    this.slideshow = this.slideshow.bind(this)
  }


  slideshow() {
    const slidesList = [
      './assets/pics/01.jpg',
      './assets/pics/02.jpg',
      './assets/pics/03.jpg',
      './assets/pics/04.jpg',
      './assets/pics/05.jpg',
      './assets/pics/06.jpg',
    ]

    return (
      <Slideshow
        autoplay
        slideInterval={500}
        defaultIndex={0}
        slides={slidesList}
        effect={'fade'}
        height={'60%'}
        width={'60%'}
      />
    )
  }

  render() {

    return (
      <div>

            { this.slideshow() }

      </div>
    );
  }
}

export default App;
```

thanks for taking a look ~~

**Comment by SeanFelipe** [comment]
package.json: 

```{
  "name": "fledm-simple",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "15.5",
    "react-scripts": "1.1.4",
    "react-slidez": "^0.0.28"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```

**Comment by Pau1fitz** [comment]
hmmm, it's working fine for me - https://codesandbox.io/s/ov694lyr46

which version of the library are you using, and are you sure that the the images are being correctly referenced? Can you send over your folder structure for the project?

**Comment by SeanFelipe** [comment]
Thanks for the working code, I bet I can make this happen by getting more in line with your approach.

Current subfolders of `src`:
```./App.css
./index.js
./assets
./assets/pics
./assets/pics/01.jpg
./assets/pics/03.jpg
./assets/pics/02.jpg
./assets/pics/06.jpg
./assets/pics/07.jpg
./assets/pics/05.jpg
./assets/pics/10.jpg
./assets/pics/04.jpg
./assets/pics/09.jpg
./assets/pics/08.jpg
./App.js```

**Comment by Pau1fitz** [comment]
ah that is most likely the issue here.

have you bootstrapped your project using `create-react-app`?

**Comment by SeanFelipe** [comment]
Pretty sure I did.

Here is a wrinkle -- I put my code up on the sandbox here:
https://codesandbox.io/s/7ok8zrvknq

I'm using web url's for my images now as opposed to filesystem references. My code is pretty much exactly like your demo code as far as I can tell ... but I'm actually still seeing the problem on codesandbox. The image refs are valid -- go to them directly and you'll see the image.

**Comment by SeanFelipe** [comment]
Could my images be too big? I have been using another CSS based approach which works but uses CSS background-image to fit the image in the div. Full size they are bigger than the browser potentially though. Not raw from the camera but still big.

**Comment by Pau1fitz** [comment]
try using `require`, I think the following should work

    const slidesList = [
      require('./assets/pics/01.jpg'),
      require('./assets/pics/02.jpg'),
      require('./assets/pics/03.jpg'),
      require('./assets/pics/04.jpg'),
    ];

**Comment by SeanFelipe** [comment]
holy shiteballs require works !!
