### ISSUE TITLE
Sample images

### ISSUE THREAD

**Issue by kstratis** [Pau1fitz/react-slidez#9]
Just writing this up to let you know that the first few example pics [here](https://pau1fitz.github.io/react-slidez/) are basically depicting a brothel in Greece. 

I'm not offended or anything just thought to give you the heads-up in case you missed it.

If that was intentional, then well.. the lib really stands out!

**Comment by Pau1fitz** [comment]
I definitely didn't know that, just thought they were nice and colorful -😄

**Comment by kstratis** [comment]
oh... indeed they are! :)

**Comment by Pau1fitz** [comment]
good man, tell them all I said hi! 👋🏼
